In [1]:
# import libraries
import numpy as np
import pandas as pd

In [24]:
data = pd.read_csv('h1b_datahubexport-2020.csv',skiprows=1)
data

,Fiscal Year,Employer,Initial Approval,Initial Denial,Continuing Approval,Continuing Denial,NAICS,Tax ID,State,City,ZIP
0,2020,NaN,0,1,0,0,71,3557.0,NY,ASTORIA,11106.0
1,2020,NaN,0,0,1,0,62,458.0,CA,EMERYVILLE,94608.0
2,2020,NaN,1,0,0,0,54,777.0,CA,GLENDORA,91740.0
3,2020,01INTERACTIVE INC,1,1,0,0,54,9852.0,CA,CITY OF INDUSTRY,91745.0
4,2020,01INTERACTIVE INC,0,1,0,0,54,9852.0,CA,HACIENDA HEIGHTS,91745.0
...,...,...,...,...,...,...,...,...,...,...,...
55234,2020,ZYWIE INC,0,0,1,0,54,9321.0,GA,DULUTH,30097.0
55235,2020,ZYXEL COMMUNICATIONS INC,0,0,1,0,33,160.0,CA,ANAHEIM,92806.0
55236,2020,ZYZYX INC,0,0,2,0,54,8307.0,CA,MILPITAS,95035.0
55237,2020,ZZOUNDS MUSIC LLC,0,0,1,0,45,7798.0,IL,CHICAGO,60654.0
55238,2020,ZZZS INC,0,0,1,0,44,7355.0,CA,SAN FRANCISCO,94129.0

In [35]:
endata= data[data['NAICS']==81]
totala = sum(endata['Initial Approval']) + sum(endata['Initial Denial']) + sum(endata['Continuing Approval']) + sum(endata['Continuing Denial'])
print('H-1B total Tech applicant numbers: %s' %totala)
print('H-1B Tech applicants initial approval: %s' %sum(endata['Initial Approval']))
print('H-1B Tech applicants Continuing Approval: %s' %sum(endata['Continuing Approval']))
print('H-1B Tech applicants initial approval ratio: %%%s' % ( sum(endata['Initial Approval']) / totala * 100 ))
print('H-1B Tech applicants Continuing Approval ratio: %%%s' % ( sum(endata['Continuing Approval'])/ totala * 100 ))

H-1B total Tech applicant numbers: 1082
H-1B Tech applicants initial approval: 347
H-1B Tech applicants Continuing Approval: 620
H-1B Tech applicants initial approval ratio: %32.07024029574861
H-1B Tech applicants Continuing Approval ratio: %57.301293900184845